[package]
name = "paramgen"
version = "0.1.0"
authors = ["nfk93 <nfk1993@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ramp = "0.5"
rand = "0.5"
primal = "0.3"
